version: '3.8'
services:
  db:
    image: postgres
    container_name: imdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5438:5432'
volumes:
  db:
    driver: local
