server.port: 8080

spring:
  application:
    name: imdb-loader
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml

imdb.source: "C:/imdb/zip"

logging.level:
  ROOT: INFO
  org.springframework: DEBUG
  org.springframework.batch: DEBUG
  org.springframework.boot.autoconfigure.logging: INFO
  com.unrec.imdb.search: DEBUG
  org.springframework.batch.repeat.support.RepeatTemplate: WARN
---
spring.config.activate.on-profile: camel
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration
---
spring.config.activate.on-profile: batch
spring.batch.jdbc.initialize-schema: never
spring.autoconfigure.exclude: org.apache.camel.spring.boot.CamelAutoConfiguration
spring.batch.job.enabled: true
batch.scheduler:
  enabled: false
  cron: "0 0 0 1 * ?"
imdb:
  basics:
    chunkSize: 10000
    enabled: false
  ratings:
    chunkSize: 10000
    enabled: false
  crew:
    chunkSize: 10000
    enabled: true
---
spring.config.activate.on-profile: dev-pg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        generate_statistics: true
#        jdbc.batch_size: 30
#        order_inserts: true
#        cache.use_second_level_cache: false
---
spring.config.activate.on-profile: dev-h2
spring:
  datasource:
    url: jdbc:h2:mem:imdb
    username: user
    password: pass
    driverClassName: org.h2.Driver
    generate-unique-name: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /db
