server.port: 8080

spring:
  application:
    name: imdb-search-service
  liquibase:
    enabled: false
    change-log: classpath:changelog-master.xml

camel:
  imdb:
    source: "C:/imdb/zip"

logging.level:
  ROOT: INFO
  org.springframework: DEBUG
  org.springframework.boot.autoconfigure.logging: INFO
  com.unrec.imdb.search: DEBUG

---
spring.config.activate.on-profile: dev-pg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imdb?cachePrepStmts=true&useServerPrepStmts=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        generate_statistics: true
        jdbc.batch_size: 30
        order_inserts: true
        cache.use_second_level_cache: false

---
spring.config.activate.on-profile: dev-h2
spring:
  datasource:
    url: jdbc:h2:mem:imdb
    username: user
    password: pass
    driverClassName: org.h2.Driver
    generate-unique-name: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /db
