server.port: 8080

spring:
  application:
    name: imdb-loader
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml

imdb.source: "C:/imdb/zip"

logging.level:
  ROOT: INFO
  org.springframework: DEBUG
  org.springframework.batch: INFO
  org.springframework.batch.item.database.JdbcBatchItemWriter: INFO
  org.springframework.batch.repeat.support.RepeatTemplate: WARN
  org.springframework.boot.autoconfigure.logging: INFO
  org.springframework.jdbc: INFO
  org.springframework.orm: INFO
  com.unrec.imdb.search: DEBUG
---
spring.config.activate.on-profile: batch
spring.batch.jdbc.initialize-schema: never
spring.batch.job.enabled: true
batch.scheduler:
  enabled: false
  cron: "0 0 0 1 * ?"
imdb:
  basics:
    chunkSize: 10000
    enabled: false
  ratings:
    chunkSize: 10000
    enabled: false
  crew:
    chunkSize: 10000
    enabled: false
  akas:
    chunkSize: 10000
    enabled: false
  principals:
    chunkSize: 10000
    enabled: false
  episode:
    chunkSize: 10000
    enabled: false
  nameBasics:
    chunkSize: 10000
    enabled: true

---
spring.config.activate.on-profile: dev-pg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
#        generate_statistics: true
#        jdbc.batch_size: 30
#        order_inserts: true
#        cache.use_second_level_cache: false
