server.port: 8080

spring:
  application:
    name: imdb-loader
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml

imdb.source: "C:/imdb/zip"

logging.level:
  ROOT: INFO
  org.springframework: DEBUG
  org.springframework.batch: INFO
  org.springframework.batch.item.database.JdbcBatchItemWriter: INFO
  org.springframework.batch.repeat.support.RepeatTemplate: WARN
  org.springframework.boot.autoconfigure.logging: INFO
  org.springframework.jdbc: INFO
  org.springframework.orm: INFO
  com.unrec.imdb.search: DEBUG
---
spring.config.activate.on-profile: batch
spring.batch.jdbc.initialize-schema: never
spring.batch.job.enabled: true
imdb:
  akas:
    enabled: true
  basics:
    enabled: true
  crew:
    enabled: true
  episode:
    enabled: true
  nameBasics:
    enabled: true
  principals:
    enabled: true
  ratings:
    enabled: true
---
spring.config.activate.on-profile: dev-pg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/imdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
